# Generated by Django 5.2.7 on 2025-11-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_preferido', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('role-playing-games-rpg', 'RPG'), ('indie', 'Indie'), ('shooter', 'Shooter'), ('sports', 'Sports'), ('strategy', 'Strategy'), ('simulation', 'Simulation')], max_length=50)),
                ('plataforma_preferida', models.CharField(choices=[('4', 'PC'), ('187', 'PS5'), ('1', 'Xbox One'), ('18', 'PS4'), ('7', 'Switch'), ('3', 'iOS'), ('21', 'Android')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
